version: '3'
services:
  product-db:
   image: postgres
   container_name: product-db
   environment:
     POSTGRES_USER: product
     POSTGRES_PASSWORD: product
     POSTGRES_DB: product
   ports:
     - 5432:5432
   networks:
     - microservices

  auth-db:
   image: postgres
   container_name: auth-db
   environment:
     POSTGRES_USER: auth
     POSTGRES_PASSWORD: auth
     POSTGRES_DB: auth
   ports:
     - 5433:5433
   networks:
     - microservices
  
  sales-db:
   image: tutum/mongodb
   container_name: sales-db
   environment:
     MONDODB_USER: sales
     MONDODB_PASS: sales
     MONDODB_DATABASE: sales
   ports:
     - 27017:27017
     - 28017:28017
   networks:
     - microservices

  rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq
   ports:
     - 5672:5672
     - 15672:15672
   networks:
     - microservices

  auth-api:
   image: matheusrfa/auth-api
   container_name: auth-api
   build: ./auth-api
   environment:
     PORT: 8080 
   ports:
     - 8080:8080
   depends_on:
     - auth-db
   networks:
     - microservices
  
  product-api:
   image: matheusrfa/product-api
   container_name: product-api
   build: ./product-api
   environment:
     PORT: 8081
   ports:
     - 8081:8081
   depends_on:
     - product-db
   networks:
     - microservices

  sales-api:
    image: matheusrfa/sales-api
    container_name: sales-api
    build: ./sales-api
    environment:
      PORT: 8082
    ports:
      - 8082:8082
    depends_on:
      - sales-db
    networks:
      - microservices   

networks:
  microservices:
    driver: bridge
  

