server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product
    username: product
    password: product
    initiialize: true
    max-active: 10
    sql:
      init:
        platform: postgresql
        mode: always
        continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
